language: c
compiler:
  - clang
  - gcc
env:
  - CFLAGS=-Werror -g -ggdb -Wfatal-errors -Wall -Wextra -pedantic -D DEBUG
  - CFLAGS=-O3
addons:
  apt:
    packages:
    - valgrind
script:
  - make -d --environment-overrides test